### ISSUE TITLE
May not emit last line.

### ISSUE THREAD

**Issue by tracker1** [soldair/node-line-stream#2]
When the last line in a file doesn't have a line ending, the value of the last line is swallowed, and not piped through.

**Comment by soldair** [comment]
thats no fun. happy to accept prs for this if you like

**Comment by soldair** [comment]
it looks like i emit the last line as a fragment event
https://github.com/soldair/node-line-stream/blob/master/index.js#L35

there are also really more modern libraries for this. i recommend split2
https://www.npmjs.com/package/split2
